import React, {useEffect, useState} from 'react';
import {View} from 'react-native';
import style from '../styles/HomePageStyle';
import SearchBar from '../components/SearchBar';
import VotesContainer from '../containers/VotesContainer';

const data = [
  {
    vote_id: 1,
    first_name: 'MARKO',
    last_name: 'KNEŽEVIĆ',
    full_name: 'MARKO KNEŽEVIĆ',
    parent_name: 'ČEDO',
    birth_date: '1994-10-01T00:00:00.000Z',
    birth_place: 'BANJA LUKA',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'RATKO JOKIĆ',
    phone_number: '38765,,,,,,,,,',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 1,
    from_cik: 1,
  },
  {
    vote_id: 2,
    first_name: 'DRAGOSLAV',
    last_name: 'MIĆOVIĆ',
    full_name: 'DRAGOSLAV MIĆOVIĆ',
    parent_name: 'NEBOJŠA',
    birth_date: '1971-11-24T00:00:00.000Z',
    birth_place: 'NOVI SAD',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '38765111111',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 3,
    first_name: 'SELMA',
    last_name: 'ŠKRBIĆ',
    full_name: 'SELMA ŠKRBIĆ',
    parent_name: 'HAZIM',
    birth_date: '1955-08-22T00:00:00.000Z',
    birth_place: 'KOTOR VAROŠ',
    sex: 'Ž',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 4,
    first_name: 'VLADIMIR',
    last_name: 'MAKSIMOVIĆ',
    full_name: 'VLADIMIR MAKSIMOVIĆ',
    parent_name: 'ZORAN',
    birth_date: '1997-08-08T00:00:00.000Z',
    birth_place: 'BANJA LUKA',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 5,
    first_name: 'LUKA',
    last_name: 'MACANOVIĆ',
    full_name: 'LUKA MACANOVIĆ',
    parent_name: 'MILE',
    birth_date: '1979-05-24T00:00:00.000Z',
    birth_place: 'KLJUČ',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 6,
    first_name: 'NIHAD',
    last_name: 'HASANBAŠIĆ',
    full_name: 'NIHAD HASANBAŠIĆ',
    parent_name: 'ZIJAD',
    birth_date: '1932-09-05T00:00:00.000Z',
    birth_place: 'BANJA LUKA',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 7,
    first_name: 'NADILA IDA',
    last_name: 'NALVIN',
    full_name: 'NADILA IDA NALVIN',
    parent_name: 'ZIJAHUDIN',
    birth_date: '1938-06-29T00:00:00.000Z',
    birth_place: 'SARAJEVO',
    sex: 'Ž',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 8,
    first_name: 'VLAJKO',
    last_name: 'KECMAN',
    full_name: 'VLAJKO KECMAN',
    parent_name: 'ŽIVKO',
    birth_date: '1949-08-13T00:00:00.000Z',
    birth_place: 'BAKINCI',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 9,
    first_name: 'MILAN',
    last_name: 'PEJIĆ',
    full_name: 'MILAN PEJIĆ',
    parent_name: 'JOVO',
    birth_date: '1952-08-27T00:00:00.000Z',
    birth_place: 'GRBAVCI',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 10,
    first_name: 'SARA',
    last_name: 'JEVĐENIĆ',
    full_name: 'SARA JEVĐENIĆ',
    parent_name: 'MILE',
    birth_date: '1994-01-14T00:00:00.000Z',
    birth_place: 'BANJA LUKA',
    sex: 'Ž',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 11,
    first_name: 'DRAGOMIR',
    last_name: 'MAJKIĆ',
    full_name: 'DRAGOMIR MAJKIĆ',
    parent_name: 'ĐORĐO',
    birth_date: '1954-04-17T00:00:00.000Z',
    birth_place: 'POTKALINJE',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 12,
    first_name: 'MIHAJLO',
    last_name: 'ORLOVIĆ',
    full_name: 'MIHAJLO ORLOVIĆ',
    parent_name: 'MIRKO',
    birth_date: '1950-09-01T00:00:00.000Z',
    birth_place: 'BOSANSKI MILANOVAC',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 13,
    first_name: 'NATAŠA',
    last_name: 'ROKVIĆ',
    full_name: 'NATAŠA ROKVIĆ',
    parent_name: 'NIKOLA',
    birth_date: '1968-03-05T00:00:00.000Z',
    birth_place: 'BANJA LUKA',
    sex: 'Ž',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 14,
    first_name: 'MILKA',
    last_name: 'DUVNJAK',
    full_name: 'MILKA DUVNJAK',
    parent_name: 'VESELKO',
    birth_date: '1959-06-22T00:00:00.000Z',
    birth_place: 'RAJIĆKE',
    sex: 'Ž',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 15,
    first_name: 'JOVANA',
    last_name: 'IGNJATIĆ',
    full_name: 'JOVANA IGNJATIĆ',
    parent_name: 'GORAN',
    birth_date: '1993-01-30T00:00:00.000Z',
    birth_place: 'BANJA LUKA',
    sex: 'Ž',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 16,
    first_name: 'STANISLAV',
    last_name: 'TRIVUNDŽA',
    full_name: 'STANISLAV TRIVUNDŽA',
    parent_name: 'NIKOLA',
    birth_date: '1959-07-01T00:00:00.000Z',
    birth_place: 'OBROVAC',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 17,
    first_name: 'TARIK',
    last_name: 'BIŠČEVIĆ',
    full_name: 'TARIK BIŠČEVIĆ',
    parent_name: 'AHMED',
    birth_date: '1956-07-30T00:00:00.000Z',
    birth_place: 'BANJA LUKA',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 18,
    first_name: 'NEĐELJKA',
    last_name: 'OPAČIĆ',
    full_name: 'NEĐELJKA OPAČIĆ',
    parent_name: 'OSTOJA',
    birth_date: '1943-03-17T00:00:00.000Z',
    birth_place: 'KAOCI',
    sex: 'Ž',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 19,
    first_name: 'JELENKO',
    last_name: 'JANKOVIĆ',
    full_name: 'JELENKO JANKOVIĆ',
    parent_name: 'BOGDAN',
    birth_date: '1997-04-03T00:00:00.000Z',
    birth_place: 'BANJA LUKA',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 20,
    first_name: 'DIVNA',
    last_name: 'MATERIĆ',
    full_name: 'DIVNA MATERIĆ',
    parent_name: 'DRAGO',
    birth_date: '1971-05-03T00:00:00.000Z',
    birth_place: 'DRVAR',
    sex: 'Ž',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
  {
    vote_id: 21,
    first_name: 'DRAGOSLAV',
    last_name: 'LUKIĆ',
    full_name: 'DRAGOSLAV LUKIĆ',
    parent_name: 'ZDRAVKO',
    birth_date: '1939-07-11T00:00:00.000Z',
    birth_place: 'BANJA LUKA',
    sex: 'M',
    city: 'Banja Luka (034)',
    delete_request: 0,
    voting_box: '034B038',
    delegated: 'CIK',
    phone_number: '',
    added: 1,
    vote_unit_id: 3,
    vote_unit: 'Izborna jedinica 3',
    created_at: '2020-09-27T18:17:56.000Z',
    status: 0,
    safe_vote: 0,
    from_cik: 1,
  },
];

const HomePage = ({navigation}) => {
  const [votes, setVotes] = useState([]);

  useEffect(() => {
    setVotes(data);
  }, [votes]);

  return (
    <View style={style.container}>
      <SearchBar />
      <VotesContainer votes={votes} />
    </View>
  );
};

export default HomePage;
